services:
  postgres:
    image: postgres:13.2
    restart: unless-stopped
    container_name: table_ui_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/db_config/postgresql.conf

  mongo:
    image: "mongo:6.0"
    container_name: "mantistable_mongo"
    env_file:
      - ./.env
    ports:
      - "27020:27017"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo-data:/data/db

  api:
    build:
      context: ./plugins
    container_name: plugins_api
    env_file:
      - ./.env
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    ports:
      - "${PLUGINS_PORT}:5000"
    restart: unless-stopped
    volumes:
      - ./plugins/app/:/plugins
    depends_on:
      - mongo
      - postgres

  mantistable:
    build: .
    restart: unless-stopped
    container_name: mantistable_next
    env_file:
      - ./.env
    environment:
      - SKIP_ENV_VALIDATION=true
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "${MANTIS_OUTSIDEPORT}:3000"
    depends_on:
      - postgres
      - mongo
      - api
